[package]
name = "tutor-db"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.10.2"
chrono = {version = "0.4.40", features = ["serde"]}
serde = {version = "1.0.219", features = ["derive"]}
